
package freakrware.wdd.server.resources;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import android.os.Environment;


public class DataBase implements WDD_interface{

	private static Connection dbVerbindung = null;
	private static Statement stmt = null;
	public ResultSet rs = null;
	public String strsql = null;
	
	{
	    try {
	        Class.forName(DB_DRIVER);
	    	
	    } catch (ClassNotFoundException e) {
	        e.printStackTrace();
	    }
	}
	public DataBase(){
		
		initialisiern_datenbank();
		
	}
	public boolean user_exists(String name){
		set_strsql("SELECT "+DB_COL_USERID+" FROM "+DB_TABLE_USERNAME+" WHERE "+DB_COL_USERNAME+" = '"+ name +"'");
		
		String[] result = get_data(GETTER_USER_EXISTS);
		if(result != null){
			return true;
		}
		else{
			return false;
		}
	}
	
	public void add_data(){
		execute_update();
	}
	@SuppressWarnings("null")
	public String[] get_data(String[] getter){
		String[] result = null;
		execute_query();
		int x = 0;
		try {
			while(rs.next())
			{
				for(int y = 0;y < getter.length;y++){
					result[x]= rs.getString(getter[y]);
				x++;
				}
				
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
		close_result_set();
		return result;
		
	}
	private void execute_update(){
		try {
			stmt.executeUpdate(strsql);
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
	}
	private void execute_query(){
		try
	    {
	    rs = stmt.executeQuery(strsql);
	    } catch(SQLException e)
	    {
	      e.printStackTrace();
	    }
		
	}
	private void close_result_set(){
		try {
			rs.close();
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
	public void set_strsql(String strsql){
		this.strsql = strsql;
	}
	public String get_strsql(){
		return this.strsql ;
	}
	
	
	protected void create_database(){
		
		strsql = "CREATE TABLE "+ DB_TABLE_USERNAME +" ("+ DB_COL_USERID +" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1)PRIMARY KEY, "+ DB_COL_USERNAME +" VARCHAR(255))"; 
		try {
			stmt.executeUpdate(strsql);
		} catch (SQLException e) {
			e.printStackTrace();
		}
		strsql = "CREATE TABLE "+ DB_TABLE_USERDATA +" ("+ DB_COL_USERID +" INTEGER,"+ DB_COL_USERIP +" VARCHAR(255) ,FOREIGN KEY ("+ DB_COL_USERID +") REFERENCES "+ DB_TABLE_USERNAME +" ("+ DB_COL_USERID +"))"; 
		try {
			stmt.executeUpdate(strsql);
		} catch (SQLException e) {
			e.printStackTrace();
		}
		strsql = "CREATE TABLE "+ DB_TABLE_MESSAGES +" ("+ DB_COL_MESSAGEID +" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1)PRIMARY KEY, "+ DB_COL_MESSAGETEXT +" LONGVARCHAR)"; 
		try {
			stmt.executeUpdate(strsql);
		} catch (SQLException e) {
			e.printStackTrace();
		}
		strsql = "CREATE TABLE "+ DB_TABLE_MESSAGEBOARD +" ("+ DB_COL_ACTIONID +" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1)PRIMARY KEY,"+ DB_COL_SENTFROMUSERID +" INTEGER,"+ DB_COL_SENTTOUSERID +" INTEGER, "+ DB_COL_MESSAGEID +" INTEGER,"
					+ DB_COL_SENTTRUE +" BIT DEFAULT FALSE NOT NULL,"+ DB_COL_INCOMINGDATE +" TIMESTAMP,"
					+ "FOREIGN KEY ("+ DB_COL_SENTFROMUSERID +") REFERENCES "+ DB_TABLE_USERNAME +" ("+ DB_COL_USERID +"),"
					+ "FOREIGN KEY ("+ DB_COL_SENTTOUSERID +") REFERENCES "+ DB_TABLE_USERNAME +" ("+ DB_COL_USERID +"),"
					+ "FOREIGN KEY ("+ DB_COL_MESSAGEID +") REFERENCES "+ DB_TABLE_MESSAGES +" ("+ DB_COL_MESSAGEID +"))"; 
		try {
			stmt.executeUpdate(strsql);
		} catch (SQLException e) {
			e.printStackTrace();
		}
	
	}
	protected void initialisiern_datenbank() {
		 String newFolder = "/"+DB_FOLDER;
		 String extStorageDirectory = "";
		 try{
			 extStorageDirectory = Environment.getExternalStorageDirectory().toString();
		 }
		 catch(Exception e){
			 //e.printStackTrace();
		 }
	     
	     File myNewFolder = new File(extStorageDirectory + newFolder);
	     myNewFolder.mkdir();
		
		File path = myNewFolder; 
	    File file = new File(path, DB_NAME);
	    String filepath = file.getAbsolutePath();
	    try {
	    	dbVerbindung = DriverManager.getConnection("jdbc:hsqldb:file:"+filepath+";ifexists=true", "SA", "");
	    	dbVerbindung.setAutoCommit(true);
	    	stmt = dbVerbindung.createStatement();
	    } catch (SQLException e) {
	    	System.out.println(e.getErrorCode());
	    	if(e.getErrorCode()==-465){
	    		try {
					dbVerbindung = DriverManager.getConnection("jdbc:hsqldb:file:"+file.getAbsolutePath()+"", "SA", "");
					dbVerbindung.setAutoCommit(true);
					stmt = dbVerbindung.createStatement();
					create_database();
				} catch (SQLException e1) {
					e1.printStackTrace();
				}
		    }
	    }
	    Runtime.getRuntime().addShutdownHook(new Thread() {
	        public void run() {
	            try {
	            	if (rs != null && !rs.isClosed()){
	            		rs.close();
	            	}
	                if (!dbVerbindung.isClosed()) {
	                	dbVerbindung.close();
	                }
	            } catch (SQLException e) {
	                e.printStackTrace();
	            }
	        }
	    });
	}

}
